namespace: cletus_mccoy
name: android_adb
version: 0.1.0
readme: README.md
authors:
  - Kasper Daems
description: Manage Android devices over ADB using Ansible
license:
  - MIT

tags:
  - android
  - adb
  - automation

dependencies: {}