---
galaxy_info:
  author: Kasper Daems
  description: Manage Android device configuration via ADB
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Android
      versions: [all]
dependencies: []
